// <auto-generated />
using System;
using MedicalLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalLab.Migrations
{
    [DbContext(typeof(MedicalLabContext))]
    partial class MedicalLabContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MedicalLab.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TestTypeName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("TestTypeName");

                    b.HasIndex(new[] { "Name", "TestTypeName" }, "UniqueParameter")
                        .IsUnique();

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("MedicalLab.Models.Patient", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("PESEL")
                        .IsFixedLength();

                    b.HasKey("Code")
                        .HasName("PK__Patients__A25C5AA63D960BA2");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedicalLab.Models.Result", b =>
                {
                    b.Property<int>("TestCode")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("TestCode", "ParameterId")
                        .HasName("PK__Results__648CF3D145854DCD");

                    b.HasIndex("ParameterId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("MedicalLab.Models.Sample", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PatientCode")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .HasName("PK__Samples__A25C5AA6AFC9BB1D");

                    b.HasIndex("PatientCode");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("MedicalLab.Models.Test", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("date");

                    b.Property<int>("SampleCode")
                        .HasColumnType("int");

                    b.Property<string>("TestTypeName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TesterId")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .HasName("PK__Tests__A25C5AA605BCDABF");

                    b.HasIndex("SampleCode");

                    b.HasIndex("TestTypeName");

                    b.HasIndex("TesterId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("MedicalLab.Models.Tester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Testers");
                });

            modelBuilder.Entity("MedicalLab.Models.TestType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Name")
                        .HasName("PK__TestType__737584F739705542");

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("MedicalLab.Models.Parameter", b =>
                {
                    b.HasOne("MedicalLab.Models.TestType", "TestTypeNameNavigation")
                        .WithMany("Parameters")
                        .HasForeignKey("TestTypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Parameter__TestT__2E1BDC42");

                    b.Navigation("TestTypeNameNavigation");
                });

            modelBuilder.Entity("MedicalLab.Models.Result", b =>
                {
                    b.HasOne("MedicalLab.Models.Parameter", "Parameter")
                        .WithMany("Results")
                        .HasForeignKey("ParameterId")
                        .IsRequired()
                        .HasConstraintName("FK__Results__Paramet__3A81B327");

                    b.HasOne("MedicalLab.Models.Test", "TestCodeNavigation")
                        .WithMany("Results")
                        .HasForeignKey("TestCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Results__TestCod__398D8EEE");

                    b.Navigation("Parameter");

                    b.Navigation("TestCodeNavigation");
                });

            modelBuilder.Entity("MedicalLab.Models.Sample", b =>
                {
                    b.HasOne("MedicalLab.Models.Patient", "PatientCodeNavigation")
                        .WithMany("Samples")
                        .HasForeignKey("PatientCode")
                        .IsRequired()
                        .HasConstraintName("FK__Samples__Patient__30F848ED");

                    b.Navigation("PatientCodeNavigation");
                });

            modelBuilder.Entity("MedicalLab.Models.Test", b =>
                {
                    b.HasOne("MedicalLab.Models.Sample", "SampleCodeNavigation")
                        .WithMany("Tests")
                        .HasForeignKey("SampleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tests__SampleCod__34C8D9D1");

                    b.HasOne("MedicalLab.Models.TestType", "TestTypeNameNavigation")
                        .WithMany("Tests")
                        .HasForeignKey("TestTypeName")
                        .IsRequired()
                        .HasConstraintName("FK__Tests__TestTypeN__33D4B598");

                    b.HasOne("MedicalLab.Models.Tester", "Tester")
                        .WithMany("Tests")
                        .HasForeignKey("TesterId")
                        .IsRequired()
                        .HasConstraintName("FK__Tests__TesterId__35BCFE0A");

                    b.Navigation("SampleCodeNavigation");

                    b.Navigation("TestTypeNameNavigation");

                    b.Navigation("Tester");
                });

            modelBuilder.Entity("MedicalLab.Models.Parameter", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("MedicalLab.Models.Patient", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("MedicalLab.Models.Sample", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("MedicalLab.Models.Test", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("MedicalLab.Models.Tester", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("MedicalLab.Models.TestType", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
